version: "2"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - 5432:5432
  adminer:
    image: adminer:4.7.6
    restart: always
    ports:
      - 8080:8080